services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: docuchat_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: docuchat
      POSTGRES_USER: docuchat_user
      POSTGRES_PASSWORD: docuchat_password

    ports:
      - "5434:5432"

    volumes:
      - docuchat_postgres_data:/var/lib/postgresql/data

volumes:
  docuchat_postgres_data: